# Generated by Django 4.0.3 on 2023-11-25 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exerciser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(help_text='운동 목표', max_length=100)),
                ('level', models.CharField(choices=[('초급', '초급'), ('중급', '중급'), ('고급', '고급')], help_text='운동 수준', max_length=50)),
                ('exercise_place', models.CharField(help_text='운동 장소', max_length=100)),
                ('preferred_exercise', models.CharField(help_text='선호하는 운동 종목', max_length=100)),
                ('exercise_duration', models.IntegerField(help_text='운동 시간(분)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='루틴 제목', max_length=100)),
                ('content', models.TextField(help_text='루틴 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='루틴 생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='루틴 최근 수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exerciser_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routines.exerciser')),
            ],
        ),
    ]
